### ISSUE TITLE
JUnit dependency

### ISSUE THREAD

**Issue by ahamana** [mirage-sql/mirage#43]
The JUnit dependency is "compile" configuration.
So, build artifacts(e.g. war, jar etc) include "junit.jar" in them.
Is this correct setting?

**Comment by aadrian** [comment]
> Is this correct setting?

Yes, I think this is correct since the https://github.com/mirage-sql/mirage/tree/master/src/main/java/com/miragesql/miragesql/test package needs it.

We plan to split this project into modules: https://github.com/mirage-sql/mirage/issues/30 with the next version, so that the core won't include this functionality (or the tooling) only if explicitly imported.

**Comment by ahamana** [comment]
Oh, I see.
Many thanks for your explanation.
